version: "3.9"
services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - $DB_PORT:80
    environment:
      MARIADB_ROOT_HOST: $DB_HOST
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
  drupal:
    image: drupal
    ports:
      - 8000:80
    depends_on:
      - db
    links:
      - db