version: '3'
services:
  load-balancer:
    image: projektmotor/apache-load-balancer
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKENDS=192.168.1.101,192.168.1.102,192.168.1.103
      - BACKEND_PORT=3000
    restart: always
